package org.drools.devguide;

import org.drools.devguide.sales.model.Client;
import org.drools.devguide.sales.model.Client.ClientCategory;
import org.drools.devguide.sales.model.ClientDiscountEvaluation;

global Client.ClientCategory[] discountCategories;

rule "Apply 10 percent discount"
when
    $cde: ClientDiscountEvaluation(
        client.category memberOf discountCategories
    )
then
    $cde.setDiscount(0.1f);
end