package chapter02.rules;

import org.drools.devguide.eshop.model.OrderLine;
import org.drools.devguide.eshop.model.Discount;

rule "High Range Order - 10% Discount"
    when
        $o: Order( $lines : orderLines.size >= 2 )
        forall( OrderLine( this memberOf $lines,  $item : item)
                Item(this == $item, category == Item.Category.HIGH_RANGE)
        )
    then
        $o.setDiscount(new Discount(10.0));
end

